---
abstract: 'A Perl port of WebMachine'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  FindBin: 0
  HTTP::Message::PSGI: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  MIME::Base64: 0
  Net::HTTP: 0
  Plack::Runner: 0
  Plack::Test: 0
  Test::Fatal: 0.003
  Test::More: 0.88
  Test::NoWarnings: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Machine
requires:
  B: 0
  Carp: 0
  Data::Dumper: 0
  HTTP::Headers::ActionPack: 0.04
  HTTP::Status: 0
  Hash::MultiValue: 0
  IO::Handle::Util: 0
  List::Util: 0
  Locale::Maketext: 0
  Plack: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Util: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Web::Machine
  repository: https://github.com/stevan/webmachine-perl.git
version: 0.07
x_authority: cpan:STEVAN
