---
abstract: 'A Perl port of WebMachine'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  FindBin: 0
  HTTP::Request::Common: 0
  MIME::Base64: 0
  Plack::Test: 0
  Plack::Util: 0
  Test::Fatal: 0.003
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300018, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Machine
requires:
  B: 0
  Carp: 0
  Data::Dumper: 0
  HTTP::Headers::ActionPack: 0
  HTTP::Status: 0
  Hash::MultiValue: 0
  List::Util: 0
  Locale::Maketext: 0
  Plack: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Response: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.03
x_authority: cpan:STEVAN
