---
abstract: 'A Perl port of Webmachine'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  FindBin: 0
  HTTP::Message::PSGI: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  MIME::Base64: 0
  Net::HTTP: 0
  Plack::Runner: 0
  Plack::Test: 0
  Test::FailWarnings: 0
  Test::Fatal: 0.003
  Test::More: 0.88
  base: 0
  lib: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Machine
requires:
  B: 0
  Carp: 0
  Data::Dumper: 0
  Encode: 0
  HTTP::Headers::ActionPack: 0.07
  HTTP::Status: 0
  Hash::MultiValue: 0
  IO::Handle::Util: 0
  List::Util: 0
  Locale::Maketext: 0
  Module::Runtime: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Util: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Try::Tiny: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Web::Machine
  repository: https://github.com/stevan/webmachine-perl.git
version: 0.15
x_authority: cpan:STEVAN
x_contributors:
  - 'Andreas Marienborg <andreas.marienborg@gmail.com>'
  - 'Andrew Nelson <anelson@cpan.org>'
  - "Arthur Axel 'fREW' Schmidt <frioux@gmail.com>"
  - 'Carlos Fernando Avila Gratz <cafe@q1software.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Fayland Lam <fayland@gmail.com>'
  - 'George Hartzell <hartzell@alerce.com>'
  - 'Gregory Oschwald <goschwald@maxmind.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'John SJ Anderson <genehack@genehack.org>'
  - 'Mike Raynham <enquiries@mikeraynham.co.uk>'
  - 'Mike Raynham <mike.raynham@spareroom.co.uk>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Thomas Sibley <tsibley@cpan.org>'
